### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by rag-hav** [izanaginookami10/web_to_epub#1]
Works flawlessly. 
Just a little thing. If 'n' is selected to download the whole novel then maybe the resulting epub file's title should not contain chapter_s and chapter_e but only thr novel title.

**Comment by izanaginookami10** [comment]
Ah, hello. Thanks for trying it.
I'll first say I have no idea how Github truly works as I'm using it just to store version of the script, so bear with me if I'm using this wrongly.

As for the suggestion, I intentionally kept it because I planned to use it on unfinished novels mostly, so obviously I would need the chapter range. I might try to implement a trigger, like if last chapter has "end" in its title, that would make the final epub file name only be the novel title. But that sounds rather unreliable.

I'm open to suggestions though, so feel free to input whatever and thanks for the comment.

**Comment by rag-hav** [comment]
you could maybe add a flag like --full-novel

**Comment by izanaginookami10** [comment]
Hello, I know it has been too long, but I've added the finished flag while doing some minor adjustments as well.

Thanks again for the input!
